name: Build Jarvis EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Compile EXE
        run: pyinstaller --onefile --noconsole --add-data "assets;assets" src/main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Universal-Jarvis-Windows
          path: dist/main.exe
